
qs:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    host: localhost
    port: 3306
    database: quick_start
    username: root
    password: 123

  redis:
    host: localhost
    port: 6379
    database: 10
    password:
